name: CI
on:
  pull_request: { }
  release:
    types:
      - published
  push:
    branches:
      - main
jobs:
  build:
    name: Run CI Steps
    runs-on: thm-eks-prod
    permissions:
      id-token: write
      contents: read
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      CI: true
      CIRCLE_ARTIFACTS: /tmp/ci/artifacts
      CIRCLE_TEST_REPORTS: /tmp/ci/junit
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/custom-actions/setup-gradle
      - name: build
        run: ./gradlew --parallel --stacktrace --continue check
      - name: Report gradle cache size
        run: du -hs ~/.gradle/caches
      - name: Upload test reports
        uses: actions/upload-artifact@v3
        if: always()
        with:
          path: /tmp/ci/artifacts
          retention-days: 5

  publish:
    name: Publish
    runs-on: thm-eks-prod
    permissions:
      id-token: write
      contents: read
    env:
      LC_ALL: C.UTF-8
      LANG: C.UTF-8
      CI: true
      CIRCLE_ARTIFACTS: /tmp/ci/artifacts
      CIRCLE_TEST_REPORTS: /tmp/ci/junit
      KUBECONFIG: /tmp/.kube/config
    needs: build
    if: startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - uses: ./.github/custom-actions/setup-gradle
      - name: Publish
        run: |
          ./gradlew --parallel publish \
          -Dgradle.publish.key=${{ secrets.GRADLE_PUBLISH_KEY }} \
          -Dgradle.publish.secret=${{ secrets.GRADLE_PUBLISH_SECRET }}
      - name: PagerDuty Alert
        uses: theoremlp/pagerduty-alert@v1
        if: ${{ failure() }}
        with:
          pd-integration-key: ${{ secrets.PD_GHA_GLOBAL_INTEGRATION_KEY }}
          title: check-ci failed for clip-orchestrator-service
          summary: |
            CI checks (lints, unit tests, & external tests) or deployment failed on `main` for 
            clip-orchestrator-service.
          service: clip-business-hours
          severity: warning
